Fix compilation errors with clang 7.0.0
Omega_h_input.cpp:745:12: error: prior to the resolution of a defect report against ISO C++11, local variable
      'result' would have been copied despite being returned by name, due to its not matching the function return type
      ('Omega_h::any' vs 'Omega_h::NameValue') [-Werror,-Wreturn-std-move-in-c++11]